## Character portraits and the cast.
##
## Sprites live in game/characters/ and are regenerated by
## tools/make_portraits.py. They are placeholders: each has a distinct
## silhouette and palette so the cast is legible, and real artwork can replace
## them file-for-file without changing anything below.
##
## Sprite size is 640x880, so the default transforms place them at the same
## height and scale only by the factor between the project's 1920x1080
## virtual resolution and the sprite width.

image seoyun = "characters/seoyun.png"
image jace = "characters/jace.png"
image ciel = "characters/ciel.png"
image irene = "characters/irene.png"


## Backgrounds. Ren'Py's automatic image definition derives a name from the
## filename, but keeps underscores, so `bg_raid.png` would define `bg_raid`
## rather than `bg raid`. The script uses spaces, so define them explicitly.
##
## Generated by tools/make_backgrounds.py.

image bg raid = "images/bg_raid.png"
image bg arrival = "images/bg_arrival.png"
image bg temple = "images/bg_temple.png"
image bg ball = "images/bg_ball.png"
image bg korea = "images/bg_korea.png"


## Default placement. A sprite is anchored by its centre, so ypos is measured
## from the middle of the screen. These are tuned for 1920x1080 and will need
## a look at other window sizes.
transform sprite_center:
    xalign 0.5
    yalign 1.0
    ypos -0.08

transform sprite_left:
    xalign 0.28
    yalign 1.0
    ypos -0.08

transform sprite_right:
    xalign 0.72
    yalign 1.0
    ypos -0.08

transform sprite_far_left:
    xalign 0.14
    yalign 1.0
    ypos -0.08

transform sprite_far_right:
    xalign 0.86
    yalign 1.0
    ypos -0.08

## A speaker's portrait at the edge of the frame, for the textbox's speaker view.
transform speaker_portrait:
    xalign 0.5
    yalign 0.5
    zoom 0.42
    xoffset 640


## Cast definitions.
##
## Seoyun speaks as herself; the others are addressed by name. Colours match
## the sprite palettes so the namebox agrees with the character on screen.

define s = Character(
    "Seoyun",
    color="#c87476",
    who_outlines=[(2, "#3a2022", 0, 0)],
    )

define jace = Character(
    "Jace",
    color="#4a74ba",
    who_outlines=[(2, "#1d2a44", 0, 0)],
    )

define ciel = Character(
    "Ciel",
    color="#5a6480",
    who_outlines=[(2, "#161c2c", 0, 0)],
    )

define irene = Character(
    "Irene",
    color="#4a5c44",
    who_outlines=[(2, "#1c2418", 0, 0)],
    )
