# The script of the game goes in this file.
#
# Saintess Seoyun — chapter 1, the raid and the arrival.
#
# Portraits are placeholders generated by tools/make_portraits.py; see
# game/characters.rpy. Replaced art drops in file-for-file.

define e = Character("Eileen", color="#c87476")


label start:

    # Act 1 — the raid. Low fantasy, high-tech: the magic is a workforce, and
    # the state has already drafted everyone who has any.

    scene bg raid

    show seoyun at sprite_center

    "The portal behaves wrong. That is the whole of it, and by the time anyone"
    "understands it the line has already broken."

    "Her forces scatter. Every direction at once, and no one is ordered,"
    "because ordering them would have taken a second nobody had."

    show seoyun at sprite_center

    s "..."

    "Separated. An ordinary medic, in open country, with no way to fight her"
    "way out of anything."

    "She has done the arithmetic before. It does not come out."

    show seoyun at sprite_center

    s "I can't. I can't do this again."

    "Small. Abandoned. Unseen. The moment everything else is built on top of,"
    "and the game does not tell you that yet."

    "Then her phone lights up and opens a door she did not ask for."

    hide seoyun
    scene bg arrival
    show seoyun at sprite_center

    # Act 2 — arrival. She is alive, which she had not planned on, and the one
    # thing she can do here is the one thing nobody else in this kingdom can.

    "She lands somewhere that looks like the world she fell out of, which is not"
    "the same as being anywhere she chose."

    s "...where am I."

    "Then someone is bleeding, and her hands move before she has decided anything."

    s "Hold still. Hold still, I'm — I can do this, I've done this."

    "A single C-rank medic. In a kingdom with no healing mages of its own."
    "It is a miracle, and the kingdom is very clear about what miracles are."

    scene bg temple
    show seoyun at sprite_center

    "They put her in a temple, which is beautiful, and cold, and full of people"
    "who are always watching, and they call her a saintess sent by god."

    s "I didn't agree to any of this."

    "Nobody asked. Being the saint is also how she is prevented from being"
    "anything else, and she does not work that out yet."

    hide seoyun

    return
